### ISSUE TITLE
deprecation warning in newer versions of node

### ISSUE THREAD

**Issue by acommodari** [OpenDataFormats/worldcities#29]
`[DEP0128] DeprecationWarning: Invalid 'main' field in '/app/available_modules/1677621557000/worldcities/package.json' of 'dist/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)`

Getting this message in node 18 and I believe that this also occurs in node 16. Seems to be an issue with `package.json`.

**Comment by acommodari** [comment]
hey @davidarvan  sorry to bother you was wondering if there was any eta for this to be addressed? If you want I could also try looking into it and opening a PR

Thanks again!

**Comment by davidarvan** [comment]
Hey Alessandro,

Sorry for the late reply. I'm looking into it today and should be able to
push an updated package. I'll let you know as soon as it is deployed.

David

**Comment by davidarvan** [comment]
Hey Alessandro,

I have just pushed an updated version of the package to npmjs. I tested it
locally with node version 18.15.0 and it works. Try updating your package
to the latest version, the error message should be fixed. Let me know and
I'll close the issue.

David

**Comment by acommodari** [comment]
Sorry for the late reply! Yes this fixes the issue thank you so much 👍 🚀
